### ISSUE TITLE
Query re: json-simple dependency

### ISSUE THREAD

**Issue by Cliabhach** [contentstack/contentstack-utils-java#5]
Hello! First off, thanks for working on Contentstack - it's been really useful.

My question is about [one of the dependencies](https://github.com/contentstack/contentstack-utils-java/blob/dffe972ba/pom.xml#L103-L108) that #3 added to the `pom.xml`. If I understand the content of [the pom.xml for `com.googlecode.json-simple:json-simple:1.1.1`](https://search.maven.org/artifact/com.googlecode.json-simple/json-simple/1.1.1/bundle) correctly, that makes this project include a transitive dependency on junit in the `compile` scope.

If this is the case, may I request that the `json-simple` dependency be modified (perhaps with an `<exclusion>` tag for junit) or replaced with another library?

**Comment by ishaileshmishra** [comment]
Thanks for writing us @Cliabhach, We can add the `<exclusion>` tag to the `json-simple` dependency
